services:
  task-management-system:
    container_name: task-management-system-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - task-management-api-db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8081"


  task-management-api-db:
    container_name: task-management-system-api
    image: postgres:14.12
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=Europe/Moscow
    expose:
      - "5432"
    volumes:
      - ../../config/postgres/apartment/postgres_data:/var/lib/postgresql/data/
